### ISSUE TITLE
Lily Periodic Actor Dump

### ISSUE THREAD

**Issue by Terryhung** [filecoin-project/lily#1252]
Lily generates real-time data at each epoch, mainly state change information. Yet, this format hinders a complete overview of actor states. To address this, we're enhancing Lily to periodically capture actor data for more practical analysis and output utilization.

**Tasks**:
- [ ] Add new processor for handling this new type task
- [ ] Implement the first task: `fevm_actor_dump`
- [ ] Add new schema for `fevm_actor_dump`
- [ ] Enable the execution of this task within both the walk and watch jobs.
- [ ] Introduce a new parameter for the walk and watch jobs to regulate the interval for actor data dumping: `--interval`.
- [ ] Implement new task: `storage_market_actor_dump`
- [ ] Implement new task: `storage_miner_actor_dump`

**document**
-  [notion](https://www.notion.so/pl-strflt/Lily-Periodic-Actor-State-Dump-f2773352ee6c4fff8bd38be9d6ebcee8)
