### ISSUE TITLE
Missing data via SectorInfo, V7SectorInfo, SectorDeals, and MinerLockedFunds Extractors.

### ISSUE THREAD

**Issue by frrist** [filecoin-project/lily#997]
### Describe the bug:
The following extractors contain a bug that causes them to miss data while extracting their respective models:
- [V7SectorInfoExtractor](https://github.com/filecoin-project/lily/blob/v0.10.0/tasks/actorstate/miner/sectorv7.go): Extracts the latest state of miner sectors for all miners using actor version v7-vN forward (includes snapped sectors)
    - [Code section with bug](https://github.com/filecoin-project/lily/blob/v0.10.0/tasks/actorstate/miner/sectorv7.go#L39-L52)
    - Model effected: miner_sector_infos_v7
    - Fix:  https://github.com/filecoin-project/lily/pull/990
- [SectorInfoExtractor](https://github.com/filecoin-project/lily/blob/v0.10.0/tasks/actorstate/miner/sector.go): Extracts the latest state of miner sectors for all miners using actor version v0-v6 (doesn’t include snapped sectors)
    - [Code section with bug](https://github.com/filecoin-project/lily/blob/v0.10.0/tasks/actorstate/miner/sector.go#L39-L49)
    - Model effected: miner_sector_infos
    - Fix:  https://github.com/filecoin-project/lily/pull/990
- [SectorDealsExtractor](https://github.com/filecoin-project/lily/blob/v0.10.0/tasks/actorstate/miner/sector_deals.go): Extracts a mapping of Deal IDs to their respective Miner and Sector IDs.
    - [Code section with bug](https://github.com/filecoin-project/lily/blob/v0.10.0/tasks/actorstate/miner/sector_deals.go#L39-L51)
    - Model effected: miner_sector_deals
    - Fix:  https://github.com/filecoin-project/lily/pull/990
 - MinerLockedFundsExtractor: Extractors details of Miner funds locked and unavailable for use.
    - [Code Section with bug](https://github.com/filecoin-project/lily/blob/v0.10.0/chain/indexer/integrated/tipset.go#L113-
L116)
    - Model effected: miner_locked_funds
    - Fix: https://github.com/filecoin-project/lily/pull/996

These bugs causes the models miner_sector_infos, miner_sector_infos_v7, and miner_sector_deals to undercount data and miner_locked_funds to miss all data, thus queries over these tables will not accurately represent the state of the chain. The models miner_sector_infos and miner_sector_infos_v7 record the state of newly added sectors:
- Height and StateRoot a sector was added
- Miner adding the sector and ID of the sector
- Sectors SealedCID, ActivationEpoch, ExpirationEpoch, DealWeight, InitialPledge, ExpectedDayReward, ExpectedStoragePledge, and if the sector contains verified data

The model miner_sector_deals records which deals belong to which sectors:
- Height deal was added to a sector
- Miner adding sector and its ID
- DealID’s contained in the sector.

The model miner_locked_funds records details of miner funds locked for adding sectors:
- Height funds were changed
- MinerID, initial pledge, pre-commit deposit, and locked funds.

It is worth pointing out that the model miner_sector_events is not affected by this and aggregations over its data will still return accurate counts of the different miner sector events (sectors added, snapped, faulted, recovered, etc.)

### Lily Version: v0.9.0 - v0.10.0
This bug affects lily v0.9.0 and v0.10.0

#### TODO:
- [ ] Release lily v0.10.1 with fix.
- [ ] Backfill analysis database from April 29th forward.
- [ ] Produce lily data exports for affected tables from April 29th forward.

**Comment by frrist** [comment]
Release candidate created here: https://github.com/filecoin-project/lily/tree/v0.10.1-rc1
